'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WmxFileUploaderCustomEvent } from "@webmobix/file-uploader";
import type { Components } from "@webmobix/file-uploader/dist/components";
import { WmxFileUploader as WmxFileUploaderElement, defineCustomElement as defineWmxFileUploader } from "@webmobix/file-uploader/dist/components/wmx-file-uploader.js";

export type WmxFileUploaderEvents = {
    onWmxFilesChanged: EventName<WmxFileUploaderCustomEvent<{ files: File[] }>>,
    onWmxFileRejected: EventName<WmxFileUploaderCustomEvent<{ files: File[] }>>
};

export const WmxFileUploader: StencilReactComponent<WmxFileUploaderElement, WmxFileUploaderEvents, Components.WmxFileUploader> = /*@__PURE__*/ createComponent<WmxFileUploaderElement, WmxFileUploaderEvents, Components.WmxFileUploader>({
    tagName: 'wmx-file-uploader',
    elementClass: WmxFileUploaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onWmxFilesChanged: 'wmxFilesChanged',
        onWmxFileRejected: 'wmxFileRejected'
    } as WmxFileUploaderEvents,
    defineCustomElement: defineWmxFileUploader
});
