/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WmxFileUploader {
        /**
          * Comma-separated MIME types and/or extensions (e.g. `image/*,.pdf`).
          * @default ''
         */
        "accept": string;
        /**
          * When true, allows selecting multiple files. When false, holds at most one.
          * @default false
         */
        "multiple": boolean;
    }
}
export interface WmxFileUploaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWmxFileUploaderElement;
}
declare global {
    interface HTMLWmxFileUploaderElementEventMap {
        "wmxFilesChanged": { files: File[] };
        "wmxFileRejected": { files: File[] };
    }
    interface HTMLWmxFileUploaderElement extends Components.WmxFileUploader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWmxFileUploaderElementEventMap>(type: K, listener: (this: HTMLWmxFileUploaderElement, ev: WmxFileUploaderCustomEvent<HTMLWmxFileUploaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWmxFileUploaderElementEventMap>(type: K, listener: (this: HTMLWmxFileUploaderElement, ev: WmxFileUploaderCustomEvent<HTMLWmxFileUploaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWmxFileUploaderElement: {
        prototype: HTMLWmxFileUploaderElement;
        new (): HTMLWmxFileUploaderElement;
    };
    interface HTMLElementTagNameMap {
        "wmx-file-uploader": HTMLWmxFileUploaderElement;
    }
}
declare namespace LocalJSX {
    interface WmxFileUploader {
        /**
          * Comma-separated MIME types and/or extensions (e.g. `image/*,.pdf`).
          * @default ''
         */
        "accept"?: string;
        /**
          * When true, allows selecting multiple files. When false, holds at most one.
          * @default false
         */
        "multiple"?: boolean;
        /**
          * Emitted when dropped files don't match `accept`.
         */
        "onWmxFileRejected"?: (event: WmxFileUploaderCustomEvent<{ files: File[] }>) => void;
        /**
          * Emitted when files are added or removed.
         */
        "onWmxFilesChanged"?: (event: WmxFileUploaderCustomEvent<{ files: File[] }>) => void;
    }

    interface WmxFileUploaderAttributes {
        "multiple": boolean;
        "accept": string;
    }

    interface IntrinsicElements {
        "wmx-file-uploader": Omit<WmxFileUploader, keyof WmxFileUploaderAttributes> & { [K in keyof WmxFileUploader & keyof WmxFileUploaderAttributes]?: WmxFileUploader[K] } & { [K in keyof WmxFileUploader & keyof WmxFileUploaderAttributes as `attr:${K}`]?: WmxFileUploaderAttributes[K] } & { [K in keyof WmxFileUploader & keyof WmxFileUploaderAttributes as `prop:${K}`]?: WmxFileUploader[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wmx-file-uploader": LocalJSX.IntrinsicElements["wmx-file-uploader"] & JSXBase.HTMLAttributes<HTMLWmxFileUploaderElement>;
        }
    }
}
